/*
 * DataBaseWriterUIMAINView.java
 */

package databasewriteruimain;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import java.io.*;
import java.util.*;

/**
 * The application's main frame.
 */
public class DataBaseWriterUIMAINView extends FrameView {

    public DataBaseWriterUIMAINView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
       
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panel_variables = new javax.swing.JPanel();
        label_startingnum = new javax.swing.JLabel();
        text_startingnum = new javax.swing.JTextField();
        label_stateid = new javax.swing.JLabel();
        text_stateid = new javax.swing.JTextField();
        text_tablename = new javax.swing.JTextField();
        label_tablename = new javax.swing.JLabel();
        panel_files = new javax.swing.JPanel();
        button_sourceBrowse = new javax.swing.JButton();
        text_source = new javax.swing.JTextField();
        label_source = new javax.swing.JLabel();
        label_destination = new javax.swing.JLabel();
        text_destination = new javax.swing.JTextField();
        button_destinationBrowse = new javax.swing.JButton();
        tabbedPane_main = new javax.swing.JTabbedPane();
        panel_operations = new javax.swing.JPanel();
        button_cancel = new javax.swing.JButton();
        button_run = new javax.swing.JButton();
        dialog_progress = new javax.swing.JDialog();
        panel_progress = new javax.swing.JPanel();
        scroll_progress = new javax.swing.JScrollPane();
        textarea_progress = new javax.swing.JTextArea();
        dialog_file = new javax.swing.JFileChooser();

        mainPanel.setMaximumSize(mainPanel.getPreferredSize());
        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(databasewriteruimain.DataBaseWriterUIMAINApp.class).getContext().getResourceMap(DataBaseWriterUIMAINView.class);
        panel_variables.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panel_variables.border.title"))); // NOI18N
        panel_variables.setName("panel_variables"); // NOI18N

        label_startingnum.setText(resourceMap.getString("label_startingnum.text")); // NOI18N
        label_startingnum.setName("label_startingnum"); // NOI18N

        text_startingnum.setText(resourceMap.getString("text_startingnum.text")); // NOI18N
        text_startingnum.setName("text_startingnum"); // NOI18N

        label_stateid.setText(resourceMap.getString("label_stateid.text")); // NOI18N
        label_stateid.setName("label_stateid"); // NOI18N

        text_stateid.setText(resourceMap.getString("text_stateid.text")); // NOI18N
        text_stateid.setName("text_stateid"); // NOI18N

        text_tablename.setText(resourceMap.getString("text_tablename.text")); // NOI18N
        text_tablename.setName("text_tablename"); // NOI18N

        label_tablename.setText(resourceMap.getString("label_tablename.text")); // NOI18N
        label_tablename.setName("label_tablename"); // NOI18N

        javax.swing.GroupLayout panel_variablesLayout = new javax.swing.GroupLayout(panel_variables);
        panel_variables.setLayout(panel_variablesLayout);
        panel_variablesLayout.setHorizontalGroup(
            panel_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_variablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_startingnum)
                    .addComponent(label_tablename))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_tablename, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                    .addGroup(panel_variablesLayout.createSequentialGroup()
                        .addComponent(text_startingnum, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(label_stateid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_stateid, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_variablesLayout.setVerticalGroup(
            panel_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_variablesLayout.createSequentialGroup()
                .addGroup(panel_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_startingnum)
                    .addComponent(text_startingnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_stateid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_stateid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_tablename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_tablename))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_files.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panel_files.border.title"))); // NOI18N
        panel_files.setName("panel_files"); // NOI18N

        button_sourceBrowse.setText(resourceMap.getString("button_sourceBrowse.text")); // NOI18N
        button_sourceBrowse.setName("button_sourceBrowse"); // NOI18N
        button_sourceBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_sourceBrowseActionPerformed(evt);
            }
        });

        text_source.setText(resourceMap.getString("text_source.text")); // NOI18N
        text_source.setName("text_source"); // NOI18N

        label_source.setText(resourceMap.getString("label_source.text")); // NOI18N
        label_source.setName("label_source"); // NOI18N

        label_destination.setText(resourceMap.getString("label_destination.text")); // NOI18N
        label_destination.setName("label_destination"); // NOI18N

        text_destination.setName("text_destination"); // NOI18N

        button_destinationBrowse.setText(resourceMap.getString("button_destinationBrowse.text")); // NOI18N
        button_destinationBrowse.setName("button_destinationBrowse"); // NOI18N
        button_destinationBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_destinationBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_filesLayout = new javax.swing.GroupLayout(panel_files);
        panel_files.setLayout(panel_filesLayout);
        panel_filesLayout.setHorizontalGroup(
            panel_filesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_filesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_filesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_destination, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_source, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_filesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_destination, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(text_source, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_filesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_sourceBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_destinationBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_filesLayout.setVerticalGroup(
            panel_filesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_filesLayout.createSequentialGroup()
                .addGroup(panel_filesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_source)
                    .addComponent(text_source, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_sourceBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_filesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_destination)
                    .addComponent(text_destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_destinationBrowse))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane_main.setName("tabbedPane_main"); // NOI18N

        panel_operations.setName("panel_operations"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(databasewriteruimain.DataBaseWriterUIMAINApp.class).getContext().getActionMap(DataBaseWriterUIMAINView.class, this);
        button_cancel.setAction(actionMap.get("quit")); // NOI18N
        button_cancel.setText(resourceMap.getString("button_cancel.text")); // NOI18N
        button_cancel.setName("button_cancel"); // NOI18N

        button_run.setText(resourceMap.getString("button_run.text")); // NOI18N
        button_run.setName("button_run"); // NOI18N
        button_run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_runActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_operationsLayout = new javax.swing.GroupLayout(panel_operations);
        panel_operations.setLayout(panel_operationsLayout);
        panel_operationsLayout.setHorizontalGroup(
            panel_operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_operationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(button_run, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel_operationsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {button_cancel, button_run});

        panel_operationsLayout.setVerticalGroup(
            panel_operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_operationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_cancel)
                    .addComponent(button_run))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane_main.addTab(resourceMap.getString("panel_operations.TabConstraints.tabTitle"), panel_operations); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_variables, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_files, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabbedPane_main))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_variables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_files, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane_main, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialog_progress.setTitle(resourceMap.getString("dialog_progress.title")); // NOI18N
        dialog_progress.setName("dialog_progress"); // NOI18N

        panel_progress.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("Progress.border.title"))); // NOI18N
        panel_progress.setName("Progress"); // NOI18N

        scroll_progress.setName("scroll_progress"); // NOI18N

        textarea_progress.setColumns(20);
        textarea_progress.setRows(5);
        textarea_progress.setName("textarea_progress"); // NOI18N
        scroll_progress.setViewportView(textarea_progress);

        javax.swing.GroupLayout panel_progressLayout = new javax.swing.GroupLayout(panel_progress);
        panel_progress.setLayout(panel_progressLayout);
        panel_progressLayout.setHorizontalGroup(
            panel_progressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_progressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll_progress)
                .addContainerGap())
        );
        panel_progressLayout.setVerticalGroup(
            panel_progressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_progressLayout.createSequentialGroup()
                .addComponent(scroll_progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout dialog_progressLayout = new javax.swing.GroupLayout(dialog_progress.getContentPane());
        dialog_progress.getContentPane().setLayout(dialog_progressLayout);
        dialog_progressLayout.setHorizontalGroup(
            dialog_progressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_progressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_progress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialog_progressLayout.setVerticalGroup(
            dialog_progressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_progressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialog_file.setApproveButtonText(resourceMap.getString("dialog_file.approveButtonText")); // NOI18N
        dialog_file.setBackground(resourceMap.getColor("dialog_file.background")); // NOI18N
        dialog_file.setDialogTitle(resourceMap.getString("dialog_file.dialogTitle")); // NOI18N
        dialog_file.setName("dialog_file"); // NOI18N

        setComponent(mainPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void button_sourceBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_sourceBrowseActionPerformed
        int returnVal = dialog_file.showDialog(mainPanel, "Use");
        if(returnVal == dialog_file.APPROVE_OPTION){
            try{
                text_source.setText(dialog_file.getSelectedFile().getPath());
            } catch (Exception e) {
                // do nothing
            }
        }
        
    }//GEN-LAST:event_button_sourceBrowseActionPerformed

    private void button_destinationBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_destinationBrowseActionPerformed
        String path1 = text_source.getText();
        File temp = new File(path1);
        File parentDir = new File(temp.getParent());
        String locationDefault =  parentDir.getPath() + "output_database.txt";
        text_destination.setText(locationDefault);
    }//GEN-LAST:event_button_destinationBrowseActionPerformed

    private void button_runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_runActionPerformed
        dialog_progress.setVisible(true);
        textarea_progress.setText("\n");
        textarea_progress.append("Beginning Operation.\n");
        int i = 0;
        try{
            PrintWriter dataOutput = new PrintWriter(new File(text_destination.getText()));
            Scanner sourceFile = new Scanner(new File(text_source.getText()));
            String buffer = "";
            String buffer2 = "";
            String buffer_sub = "";
            String template = "INSERT INTO \'"+text_tablename.getText()+"\' VALUES(303, \'\', \'\', \'1\');";
            while(sourceFile.hasNextLine()){
                
                buffer_sub = "";
                buffer = sourceFile.nextLine();
                char fuckit[] = buffer.toCharArray();
                for(int a = 0; a < buffer.length(); a++){
                    if(fuckit[a] == '\t'){
                        //ignore
                    } else {
                        buffer_sub += Character.toString(fuckit[a]);
                    }
                }
                buffer2 = "INSERT INTO \'"+text_tablename.getText()+"\' VALUES(" + (Integer.parseInt(text_startingnum.getText()) + i) + ", \'"+ buffer_sub +"\', \'\', \'"+ text_stateid.getText() +"\');";
                dataOutput.println(buffer2);
                textarea_progress.append("Successfully Printed: " + buffer2.substring(0, 25) + " :: Line:" + i + "\n");
                i++;
            }
            
            
            dataOutput.close();
            textarea_progress.append("Process Completed.");
            
        } catch(Exception e){
            textarea_progress.append("Process Failed.\n");
        }
    }//GEN-LAST:event_button_runActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_destinationBrowse;
    private javax.swing.JButton button_run;
    private javax.swing.JButton button_sourceBrowse;
    private javax.swing.JFileChooser dialog_file;
    private javax.swing.JDialog dialog_progress;
    private javax.swing.JLabel label_destination;
    private javax.swing.JLabel label_source;
    private javax.swing.JLabel label_startingnum;
    private javax.swing.JLabel label_stateid;
    private javax.swing.JLabel label_tablename;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panel_files;
    private javax.swing.JPanel panel_operations;
    private javax.swing.JPanel panel_progress;
    private javax.swing.JPanel panel_variables;
    private javax.swing.JScrollPane scroll_progress;
    private javax.swing.JTabbedPane tabbedPane_main;
    private javax.swing.JTextField text_destination;
    private javax.swing.JTextField text_source;
    private javax.swing.JTextField text_startingnum;
    private javax.swing.JTextField text_stateid;
    private javax.swing.JTextField text_tablename;
    private javax.swing.JTextArea textarea_progress;
    // End of variables declaration//GEN-END:variables


}
