/*
 * DataBaseWriterUIMAINView.java
 */

package databasewriteruimain;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import java.io.*;
import java.util.*;

/**
 * The application's main frame.
 */
public class DataBaseWriterUIMAINView extends FrameView {

    public DataBaseWriterUIMAINView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
       
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panel_variables = new javax.swing.JPanel();
        label_startingnum = new javax.swing.JLabel();
        text_startingnum = new javax.swing.JTextField();
        label_intervals = new javax.swing.JLabel();
        text_intervals = new javax.swing.JTextField();
        panel_files = new javax.swing.JPanel();
        label_destination = new javax.swing.JLabel();
        text_destination = new javax.swing.JTextField();
        tabbedPane_main = new javax.swing.JTabbedPane();
        panel_operations = new javax.swing.JPanel();
        button_run = new javax.swing.JButton();
        panel_advancedOptions = new javax.swing.JPanel();
        panel_advanced_variables = new javax.swing.JPanel();
        advanced_text_var1 = new javax.swing.JTextField();
        advanced_text_var2 = new javax.swing.JTextField();
        advanced_text_var3 = new javax.swing.JTextField();
        advanced_text_var4 = new javax.swing.JTextField();
        advanced_text_var5 = new javax.swing.JTextField();
        advanced_text_var6 = new javax.swing.JTextField();
        advanced_label_table = new javax.swing.JLabel();
        advanced_label_var1 = new javax.swing.JLabel();
        advanced_label_var2 = new javax.swing.JLabel();
        advanced_label_var3 = new javax.swing.JLabel();
        advanced_label_var4 = new javax.swing.JLabel();
        advanced_label_var5 = new javax.swing.JLabel();
        advanced_panel_customizable = new javax.swing.JPanel();
        advanced_radio_custDisable = new javax.swing.JRadioButton();
        advanced_radio_custEnable = new javax.swing.JRadioButton();
        advanced_label_numvar = new javax.swing.JLabel();
        advanced_text_numvar = new javax.swing.JTextField();
        panel_progress = new javax.swing.JPanel();
        scroll_progress = new javax.swing.JScrollPane();
        textarea_progress = new javax.swing.JTextArea();
        button_progress_clear = new javax.swing.JButton();
        dialog_file = new javax.swing.JFileChooser();
        advanced_bgroup_customizable = new javax.swing.ButtonGroup();

        mainPanel.setMaximumSize(mainPanel.getPreferredSize());
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(626, 480));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(databasewriteruimain.DataBaseWriterUIMAINApp.class).getContext().getResourceMap(DataBaseWriterUIMAINView.class);
        panel_variables.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panel_variables.border.title"))); // NOI18N
        panel_variables.setName("panel_variables"); // NOI18N

        label_startingnum.setText(resourceMap.getString("label_startingnum.text")); // NOI18N
        label_startingnum.setName("label_startingnum"); // NOI18N

        text_startingnum.setText(resourceMap.getString("text_startingnum.text")); // NOI18N
        text_startingnum.setName("text_startingnum"); // NOI18N

        label_intervals.setText(resourceMap.getString("label_intervals.text")); // NOI18N
        label_intervals.setName("label_intervals"); // NOI18N

        text_intervals.setText(resourceMap.getString("text_intervals.text")); // NOI18N
        text_intervals.setName("text_intervals"); // NOI18N

        javax.swing.GroupLayout panel_variablesLayout = new javax.swing.GroupLayout(panel_variables);
        panel_variables.setLayout(panel_variablesLayout);
        panel_variablesLayout.setHorizontalGroup(
            panel_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_variablesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_startingnum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_startingnum, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(label_intervals)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_intervals, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_variablesLayout.setVerticalGroup(
            panel_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_variablesLayout.createSequentialGroup()
                .addGroup(panel_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_startingnum)
                    .addComponent(text_startingnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_intervals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_intervals))
                .addContainerGap(6, Short.MAX_VALUE))
        );

        panel_files.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panel_files.border.title"))); // NOI18N
        panel_files.setName("panel_files"); // NOI18N

        label_destination.setText(resourceMap.getString("label_destination.text")); // NOI18N
        label_destination.setName("label_destination"); // NOI18N

        text_destination.setName("text_destination"); // NOI18N

        javax.swing.GroupLayout panel_filesLayout = new javax.swing.GroupLayout(panel_files);
        panel_files.setLayout(panel_filesLayout);
        panel_filesLayout.setHorizontalGroup(
            panel_filesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_filesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_destination)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_destination, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_filesLayout.setVerticalGroup(
            panel_filesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_filesLayout.createSequentialGroup()
                .addGroup(panel_filesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_destination)
                    .addComponent(text_destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane_main.setName("tabbedPane_main"); // NOI18N

        panel_operations.setName("panel_operations"); // NOI18N

        button_run.setBackground(resourceMap.getColor("button_run.background")); // NOI18N
        button_run.setFont(resourceMap.getFont("button_run.font")); // NOI18N
        button_run.setForeground(resourceMap.getColor("button_run.foreground")); // NOI18N
        button_run.setText(resourceMap.getString("button_run.text")); // NOI18N
        button_run.setName("button_run"); // NOI18N
        button_run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_runActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_operationsLayout = new javax.swing.GroupLayout(panel_operations);
        panel_operations.setLayout(panel_operationsLayout);
        panel_operationsLayout.setHorizontalGroup(
            panel_operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_operationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_run, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_operationsLayout.setVerticalGroup(
            panel_operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_operationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_run, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane_main.addTab(resourceMap.getString("panel_operations.TabConstraints.tabTitle"), panel_operations); // NOI18N

        panel_advancedOptions.setName("panel_advancedOptions"); // NOI18N

        panel_advanced_variables.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panel_advanced_variables.border.title"))); // NOI18N
        panel_advanced_variables.setName("panel_advanced_variables"); // NOI18N

        advanced_text_var1.setText(resourceMap.getString("advanced_text_var1.text")); // NOI18N
        advanced_text_var1.setName("advanced_text_var1"); // NOI18N

        advanced_text_var2.setText(resourceMap.getString("advanced_text_var2.text")); // NOI18N
        advanced_text_var2.setName("advanced_text_var2"); // NOI18N

        advanced_text_var3.setText(resourceMap.getString("advanced_text_var3.text")); // NOI18N
        advanced_text_var3.setName("advanced_text_var3"); // NOI18N

        advanced_text_var4.setText(resourceMap.getString("advanced_text_var4.text")); // NOI18N
        advanced_text_var4.setName("advanced_text_var4"); // NOI18N

        advanced_text_var5.setText(resourceMap.getString("advanced_text_var5.text")); // NOI18N
        advanced_text_var5.setName("advanced_text_var5"); // NOI18N

        advanced_text_var6.setText(resourceMap.getString("advanced_text_var6.text")); // NOI18N
        advanced_text_var6.setName("advanced_text_var6"); // NOI18N

        advanced_label_table.setText(resourceMap.getString("advanced_label_table.text")); // NOI18N
        advanced_label_table.setName("advanced_label_table"); // NOI18N

        advanced_label_var1.setText(resourceMap.getString("advanced_label_var1.text")); // NOI18N
        advanced_label_var1.setName("advanced_label_var1"); // NOI18N

        advanced_label_var2.setText(resourceMap.getString("advanced_label_var2.text")); // NOI18N
        advanced_label_var2.setName("advanced_label_var2"); // NOI18N

        advanced_label_var3.setText(resourceMap.getString("advanced_label_var3.text")); // NOI18N
        advanced_label_var3.setName("advanced_label_var3"); // NOI18N

        advanced_label_var4.setText(resourceMap.getString("advanced_label_var4.text")); // NOI18N
        advanced_label_var4.setName("advanced_label_var4"); // NOI18N

        advanced_label_var5.setText(resourceMap.getString("advanced_label_var5.text")); // NOI18N
        advanced_label_var5.setName("advanced_label_var5"); // NOI18N

        javax.swing.GroupLayout panel_advanced_variablesLayout = new javax.swing.GroupLayout(panel_advanced_variables);
        panel_advanced_variables.setLayout(panel_advanced_variablesLayout);
        panel_advanced_variablesLayout.setHorizontalGroup(
            panel_advanced_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_advanced_variablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_advanced_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(advanced_label_table)
                    .addComponent(advanced_label_var1)
                    .addComponent(advanced_label_var2)
                    .addComponent(advanced_label_var4)
                    .addComponent(advanced_label_var5)
                    .addComponent(advanced_label_var3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_advanced_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(advanced_text_var6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addComponent(advanced_text_var5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addComponent(advanced_text_var4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addComponent(advanced_text_var3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addComponent(advanced_text_var2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addComponent(advanced_text_var1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_advanced_variablesLayout.setVerticalGroup(
            panel_advanced_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_advanced_variablesLayout.createSequentialGroup()
                .addGroup(panel_advanced_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(advanced_text_var1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(advanced_label_table))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_advanced_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(advanced_text_var2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(advanced_label_var1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_advanced_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(advanced_text_var3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(advanced_label_var2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_advanced_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(advanced_text_var4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(advanced_label_var3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_advanced_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(advanced_text_var5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(advanced_label_var4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_advanced_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(advanced_text_var6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(advanced_label_var5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        advanced_panel_customizable.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("advanced_panel_customizable.border.title"))); // NOI18N
        advanced_panel_customizable.setName("advanced_panel_customizable"); // NOI18N

        advanced_bgroup_customizable.add(advanced_radio_custDisable);
        advanced_radio_custDisable.setSelected(true);
        advanced_radio_custDisable.setText(resourceMap.getString("advanced_radio_custDisable.text")); // NOI18N
        advanced_radio_custDisable.setName("advanced_radio_custDisable"); // NOI18N
        advanced_radio_custDisable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advanced_radio_custDisableActionPerformed(evt);
            }
        });

        advanced_bgroup_customizable.add(advanced_radio_custEnable);
        advanced_radio_custEnable.setText(resourceMap.getString("advanced_radio_custEnable.text")); // NOI18N
        advanced_radio_custEnable.setName("advanced_radio_custEnable"); // NOI18N
        advanced_radio_custEnable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advanced_radio_custEnableActionPerformed(evt);
            }
        });

        advanced_label_numvar.setText(resourceMap.getString("advanced_label_numvar.text")); // NOI18N
        advanced_label_numvar.setName("advanced_label_numvar"); // NOI18N

        advanced_text_numvar.setText(resourceMap.getString("advanced_text_numvar.text")); // NOI18N
        advanced_text_numvar.setEnabled(false);
        advanced_text_numvar.setName("advanced_text_numvar"); // NOI18N

        javax.swing.GroupLayout advanced_panel_customizableLayout = new javax.swing.GroupLayout(advanced_panel_customizable);
        advanced_panel_customizable.setLayout(advanced_panel_customizableLayout);
        advanced_panel_customizableLayout.setHorizontalGroup(
            advanced_panel_customizableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advanced_panel_customizableLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(advanced_radio_custDisable)
                .addGap(18, 18, 18)
                .addComponent(advanced_radio_custEnable, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(advanced_label_numvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(advanced_text_numvar, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );

        advanced_panel_customizableLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {advanced_radio_custDisable, advanced_radio_custEnable});

        advanced_panel_customizableLayout.setVerticalGroup(
            advanced_panel_customizableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advanced_panel_customizableLayout.createSequentialGroup()
                .addGroup(advanced_panel_customizableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(advanced_radio_custEnable)
                    .addComponent(advanced_radio_custDisable)
                    .addComponent(advanced_label_numvar)
                    .addComponent(advanced_text_numvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_advancedOptionsLayout = new javax.swing.GroupLayout(panel_advancedOptions);
        panel_advancedOptions.setLayout(panel_advancedOptionsLayout);
        panel_advancedOptionsLayout.setHorizontalGroup(
            panel_advancedOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_advancedOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_advancedOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(advanced_panel_customizable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_advanced_variables, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_advancedOptionsLayout.setVerticalGroup(
            panel_advancedOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_advancedOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_advanced_variables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(advanced_panel_customizable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane_main.addTab(resourceMap.getString("panel_advancedOptions.TabConstraints.tabTitle"), panel_advancedOptions); // NOI18N

        panel_progress.setFocusable(false);
        panel_progress.setName("panel_progress"); // NOI18N

        scroll_progress.setName("scroll_progress"); // NOI18N

        textarea_progress.setColumns(20);
        textarea_progress.setRows(5);
        textarea_progress.setName("textarea_progress"); // NOI18N
        scroll_progress.setViewportView(textarea_progress);

        button_progress_clear.setText(resourceMap.getString("button_progress_clear.text")); // NOI18N
        button_progress_clear.setName("button_progress_clear"); // NOI18N
        button_progress_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_progress_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_progressLayout = new javax.swing.GroupLayout(panel_progress);
        panel_progress.setLayout(panel_progressLayout);
        panel_progressLayout.setHorizontalGroup(
            panel_progressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_progressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_progressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll_progress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                    .addComponent(button_progress_clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_progressLayout.setVerticalGroup(
            panel_progressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_progressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll_progress, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_progress_clear)
                .addContainerGap())
        );

        tabbedPane_main.addTab(resourceMap.getString("panel_progress.TabConstraints.tabTitle"), panel_progress); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_variables, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_files, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabbedPane_main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_variables, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_files, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane_main, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        dialog_file.setApproveButtonText(resourceMap.getString("dialog_file.approveButtonText")); // NOI18N
        dialog_file.setBackground(resourceMap.getColor("dialog_file.background")); // NOI18N
        dialog_file.setDialogTitle(resourceMap.getString("dialog_file.dialogTitle")); // NOI18N
        dialog_file.setName("dialog_file"); // NOI18N

        setComponent(mainPanel);
    }// </editor-fold>//GEN-END:initComponents
//C:\Users\Thomas Ibarra\Documents\NetBeansProjects\AlbumWriter1\dist\test.dat
    private boolean checkCustomizableEnabled() {
        if(advanced_radio_custDisable.isSelected()) return false;
        else if(advanced_radio_custEnable.isSelected()) return true;
        else return false;
    }
    private void button_runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_runActionPerformed
        tabbedPane_main.setSelectedIndex(2);
        try{
        int n = Integer.parseInt(text_startingnum.getText());
        int endingnumber = n + Integer.parseInt(text_intervals.getText());
        
        textarea_progress.setText("\n");
        textarea_progress.append("Beginning Process.\n");
        
            PrintWriter dataOutput = new PrintWriter(new File(text_destination.getText()));
            if(!checkCustomizableEnabled()){
            String orignal_template = "INSERT INTO \'album\' VALUES(60, \'\', \'\', \'\', \'\', \'\');";
            
            for(int i = n; i < endingnumber; i++){
                String template = "INSERT INTO \'"+advanced_text_var1.getText()
                        +"\' VALUES("+i+", \'"+advanced_text_var2.getText()
                        +"\', \'"+advanced_text_var3.getText()
                        +"\', \'"+advanced_text_var4.getText()
                        +"\', \'"+advanced_text_var5.getText()
                        +"\', \'"+advanced_text_var6.getText()
                        +"\');";
                dataOutput.println(template);
                textarea_progress.append("Successfully Printed: " + template.substring(0, 25) + " :: Line:" + i + "\n");
     
                 }
            } else {
                for(int i = n; i < endingnumber; i++){
                String template2_1 = "INSERT INTO \'"+advanced_text_var1.getText() + "\' VALUES("+i+",";
                String template2_2 = "";
                String template2_3 = ");";
                int numberVars = Integer.parseInt(advanced_text_numvar.getText());
                for(int j = 0; j < numberVars; j++){
                    template2_2 += " \'\',";
                }
                String template = template2_1 + template2_2 + template2_3;
                dataOutput.println(template);
                textarea_progress.append("Successfully Printed: " + template.substring(0, 25) + " :: Line:" + i + "\n");

                 }
            }
            dataOutput.close();
            textarea_progress.append("Process Completed.");
            
        } catch(Exception e){
            textarea_progress.append("Process Failed.\n\n");
            textarea_progress.append(e.getMessage()+"\n\n");
        }
    }//GEN-LAST:event_button_runActionPerformed

    private void button_progress_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_progress_clearActionPerformed
        textarea_progress.setText("");
    }//GEN-LAST:event_button_progress_clearActionPerformed

    private void advanced_radio_custDisableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advanced_radio_custDisableActionPerformed
        advanced_text_var2.setEnabled(true);
        advanced_text_var3.setEnabled(true);
        advanced_text_var4.setEnabled(true);
        advanced_text_var5.setEnabled(true);
        advanced_text_var6.setEnabled(true);
        advanced_text_numvar.setEnabled(false);
    }//GEN-LAST:event_advanced_radio_custDisableActionPerformed

    private void advanced_radio_custEnableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advanced_radio_custEnableActionPerformed
        advanced_text_var2.setEnabled(false);
        advanced_text_var3.setEnabled(false);
        advanced_text_var4.setEnabled(false);
        advanced_text_var5.setEnabled(false);
        advanced_text_var6.setEnabled(false);
        advanced_text_numvar.setEnabled(true);
    }//GEN-LAST:event_advanced_radio_custEnableActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup advanced_bgroup_customizable;
    private javax.swing.JLabel advanced_label_numvar;
    private javax.swing.JLabel advanced_label_table;
    private javax.swing.JLabel advanced_label_var1;
    private javax.swing.JLabel advanced_label_var2;
    private javax.swing.JLabel advanced_label_var3;
    private javax.swing.JLabel advanced_label_var4;
    private javax.swing.JLabel advanced_label_var5;
    private javax.swing.JPanel advanced_panel_customizable;
    private javax.swing.JRadioButton advanced_radio_custDisable;
    private javax.swing.JRadioButton advanced_radio_custEnable;
    private javax.swing.JTextField advanced_text_numvar;
    private javax.swing.JTextField advanced_text_var1;
    private javax.swing.JTextField advanced_text_var2;
    private javax.swing.JTextField advanced_text_var3;
    private javax.swing.JTextField advanced_text_var4;
    private javax.swing.JTextField advanced_text_var5;
    private javax.swing.JTextField advanced_text_var6;
    private javax.swing.JButton button_progress_clear;
    private javax.swing.JButton button_run;
    private javax.swing.JFileChooser dialog_file;
    private javax.swing.JLabel label_destination;
    private javax.swing.JLabel label_intervals;
    private javax.swing.JLabel label_startingnum;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panel_advancedOptions;
    private javax.swing.JPanel panel_advanced_variables;
    private javax.swing.JPanel panel_files;
    private javax.swing.JPanel panel_operations;
    private javax.swing.JPanel panel_progress;
    private javax.swing.JPanel panel_variables;
    private javax.swing.JScrollPane scroll_progress;
    private javax.swing.JTabbedPane tabbedPane_main;
    private javax.swing.JTextField text_destination;
    private javax.swing.JTextField text_intervals;
    private javax.swing.JTextField text_startingnum;
    private javax.swing.JTextArea textarea_progress;
    // End of variables declaration//GEN-END:variables


}
